const STORE = "ge_intake_v2";
const state = loadState();
function loadState(){try{return JSON.parse(localStorage.getItem(STORE))||{answers:{},files:[],step:0}}catch{return{answers:{},files:[],step:0}}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state));renderPreview();renderNav();updateMeter()}
function renderNav(){const nav=document.getElementById("nav");nav.innerHTML=STEPS.map((s,i)=>{const done=stepFilled(s);return `<button class="${i===state.step?"active":""} ${done?"done":""}" onclick="go(${i})"><span class=n>${String(i).padStart(2,"0")}</span>${s.title}</button>`}).join("")}
function stepFilled(step){if(!step.fields)return false;const crit=step.fields.filter(f=>f[4]);if(!crit.length)return step.fields.some(f=>(state.answers[f[0]]||"").trim());return crit.every(f=>(state.answers[f[0]]||"").trim())}
function go(i){state.step=Math.max(0,Math.min(STEPS.length-1,i));saveState();renderScreen()}
function stepPrev(){go(state.step-1)}
function stepNext(){if(state.step===STEPS.length-1)return;go(state.step+1)}
function stepHint(id){return({identity:"Lock what the game is today.",intent:"Pillars must force cuts.",constraints:"These bound the 10/10.",machine:"Write verbs.",first:"Cold player, no designer.",repeat:"After novelty dies.",behaviour:"Only what you have seen.",problems:"Facts vs suspicions.",production:"Score the build, not the deck.",planning:"Effort sizes for this team."})[id]||""}
function renderField(f){const [id,label,type,hint,critical,tall]=f;const val=state.answers[id]||"";let control="";if(type==="select"){const opts=hint.split("|");control=`<select id=f_${id}><option value=\"\"></option>${opts.map(o=>`<option ${val===o?"selected":""}>${o}</option>`).join("")}</select>`}else if(type==="textarea"){control=`<textarea id=f_${id} class="${tall?"tall":""}">${esc(val)}</textarea>`}else{control=`<input type=text id=f_${id} value=\"${esc(val)}\" />`}return `<div class=card><label>${label}${critical?" <span style='color:var(--gold)'>*</span>":""}</label>${hint&&type!=="select"?`<p class=hint>${hint}</p>`:""}${control}<div class=field-actions><button class=ghost onclick=\"setUnknown('${id}')\">Unknown</button></div></div>`}
function renderScreen(){const step=STEPS[state.step];const root=document.getElementById("screen");const next=document.getElementById("nextBtn");next.textContent=step.kind==="generate"?"Done":(step.id==="start"?"Start intake":"Next");if(step.kind==="start"){root.innerHTML=`<h1>Build the analysis packet</h1><p class=lede>Answer what you know. Unknown is allowed. Then copy the prompt into a new Grok chat.</p><div class=card><ol class=start-list><li>Fill the intake.</li><li>Drop text notes if you have them.</li><li>Generate copies Part A + Part B.</li></ol></div>`;return}if(step.kind==="files"){root.innerHTML=`<h1>Files & notes</h1><p class=lede>Text notes, markdown, CSV, JSON. Paste PDF excerpts.</p><div class=drop id=drop>Drop files or <label class=teal style=display:inline-block;margin-left:8px>Browse<input type=file multiple hidden id=fileInput></label></div><div class=files id=fileList></div><div class=card style=margin-top:16px><label>Extra pasted notes</label><textarea class=tall id=extraNotes>${esc(state.answers.extraNotes||"")}</textarea></div>`;renderFiles();document.getElementById("extraNotes").oninput=e=>{state.answers.extraNotes=e.target.value;saveState()};document.getElementById("fileInput").onchange=e=>ingestFiles(e.target.files);const drop=document.getElementById("drop");drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();ingestFiles(e.dataTransfer.files)};return}if(step.kind==="generate"){const ready=readiness();root.innerHTML=`<h1>Generate the analysis prompt</h1><div class=card><b>Readiness: ${ready.score}%</b><p class="${ready.score>=70?"ok":"warn"}">${ready.note}</p><div class=chips>${ready.missing.map(m=>`<span class=\"chip bad\">${m}</span>`).join("")||`<span class=\"chip good\">Critical fields present</span>`}</div></div><div class=card><button class=gold onclick=copyFull()>Copy full prompt</button> <button class=teal onclick=copyIntake()>Copy intake only</button> <button class=ghost onclick=downloadFull()>Download .md</button><p class=hint id=copyStatus></p></div><div class=card><label>Packet preview</label><textarea class=tall style=min-height:280px readonly>${esc(buildFullPacket())}</textarea></div>`;return}root.innerHTML=`<h1>${step.title}</h1><p class=lede>${stepHint(step.id)}</p>`+step.fields.map(renderField).join("");step.fields.forEach(f=>{const el=document.getElementById("f_"+f[0]);if(!el)return;el.oninput=()=>{state.answers[f[0]]=el.value;saveState()}})}
function setUnknown(id){state.answers[id]="Unknown";saveState();renderScreen()}
function markSectionUnknown(){const step=STEPS[state.step];if(!step.fields)return;step.fields.forEach(f=>{if(!(state.answers[f[0]]||"").trim())state.answers[f[0]]="Unknown"});saveState();renderScreen()}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
async function ingestFiles(list){for(const file of [...list]){const rec={name:file.name,size:file.size,type:file.type,at:new Date().toISOString(),text:"",note:""};if(file.type.startsWith("image/")){rec.kind="image";rec.note="Image attached locally."}else if(/\.pdf$|\.docx$/i.test(file.name)){rec.kind="binary";rec.note="Paste excerpts instead."}else{try{const text=await file.text();if(text.startsWith("%PDF")||text.startsWith("PK")){rec.kind="binary"}else{rec.kind="text";rec.text=text.slice(0,80000)}}catch{rec.kind="unread"}}state.files.push(rec)}saveState();renderFiles()}
function renderFiles(){const box=document.getElementById("fileList");if(!box)return;if(!state.files.length){box.innerHTML=`<div class=hint>No files yet.</div>`;return}box.innerHTML=state.files.map((f,i)=>`<div class=file><b>${esc(f.name)}</b><span class=hint>${f.kind||"file"}</span><div class=field-actions><button class=danger onclick=removeFile(${i})>Remove</button></div></div>`).join("")}
function removeFile(i){state.files.splice(i,1);saveState();renderFiles()}
function ans(id,fallback="Unknown"){const v=(state.answers[id]||"").trim();return v||fallback}
function buildIntake(){return `# GAME INTAKE\n\n## 1. Identity\n- Game name: ${ans("name")}\n- Pitch: ${ans("pitch")}\n- Genre: ${ans("genre")}\n- Comparables: ${ans("comps")}\n- Platforms: ${ans("platforms")}\n- Session: ${ans("session")}\n- Build state: ${ans("buildState")}\n- Version: ${ans("version")}\n\n## 2. Intent\n- Player: ${ans("player")}\n- Fantasy: ${ans("fantasy")}\n- Pillar 1: ${ans("pillar1")}\n- Pillar 2: ${ans("pillar2")}\n- Pillar 3: ${ans("pillar3")}\n- Worse at: ${ans("worseAt")}\n- Goals: ${ans("goal1")}; ${ans("goal2")}; ${ans("goal3")}\n- Done: ${ans("dod")}\n\n## 3. Constraints\n- Team: ${ans("team")}\n- Skills: ${ans("skills")}\n- Time box: ${ans("timebox")}\n- Locks: ${ans("locks")}\n- Business: ${ans("biz")}\n- Sacred cows: ${ans("cows")}\n- Cuts: ${ans("cuts")}\n- Legal: ${ans("legal")}\n\n## 4. Machine\n- Core loop: ${ans("coreLoop")}\n- Session loop: ${ans("sessionLoop")}\n- Meta loop: ${ans("metaLoop")}\n- Onboarding: ${ans("onboarding")}\n- Time-to-fun: ${ans("ttf")}\n- Progression: ${ans("progress")}\n- Economy: ${ans("economy")}\n- Fail: ${ans("fail")}\n- Social: ${ans("social")}\n\n## 5. First session\n- 0-1: ${ans("m01")}\n- 1-5: ${ans("m15")}\n- Rest: ${ans("restFirst")}\n- Can do: ${ans("canDo")}\n- Stuck: ${ans("stuck")}\n- Bored: ${ans("bored")}\n- Thinks: ${ans("thinks")}\n\n## 6. Repeat\n- Session 2: ${ans("session2")}\n- Week 1: ${ans("week1")}\n- Week 4: ${ans("week4")}\n- Repetitive first: ${ans("repeatFirst")}\n- Ignored: ${ans("ignored")}\n\n## 7. Behaviour\n- Observed: ${ans("observed")}\n- Quotes: ${ans("quotes")}\n- Drop-off: ${ans("dropoff")}\n- Workarounds: ${ans("workarounds")}\n- Praised: ${ans("praised")}\n- Never mentioned: ${ans("neverMention")}\n- Metrics: ${ans("metrics")}\n- Footage: ${ans("footage")}\n\n## 8. Problems\n- Agreed: ${ans("agreed")}\n- Suspected: ${ans("suspected")}\n- Tried: ${ans("tried")}\n- Fights: ${ans("fights")}\n\n## 9. Production\n- Playable: ${ans("playable")}\n- Greybox: ${ans("greybox")}\n- Deck only: ${ans("deckOnly")}\n- Content gap: ${ans("contentGap")}\n- Tech risk: ${ans("techRisk")}\n\n## 10. Planning\n- Capacity: ${ans("capacity")}\n- S: ${ans("sizeS")} M: ${ans("sizeM")} L: ${ans("sizeL")} XL: ${ans("sizeXL")}\n- Unanswered: ${ans("unanswered")}\n\n## Extra notes\n${ans("extraNotes","(none)")}\n`}
let PART_B_CACHE="";
async function loadPartB(){try{const res=await fetch("PROMPT.md");PART_B_CACHE=(await res.text()).trim()}catch{PART_B_CACHE=""}}
function partB(){return PART_B_CACHE||"See PROMPT.md in this repo."}
function buildFullPacket(){return `Use the Game Intake below as source material. Then follow the analysis prompt exactly.\n\n==================================================\nGAME INTAKE\n==================================================\n${buildIntake()}\n\n==================================================\nANALYSIS PROMPT\n==================================================\n${partB()}\n`}
function readiness(){const need=[["name","Game name"],["pitch","Pitch"],["player","Player"],["fantasy","Fantasy"],["pillar1","Pillars"],["coreLoop","Core loop"],["m01","First minute"],["m15","Minutes 1-5"],["observed","Observed behaviour"],["playable","What is playable"]];const missing=need.filter(([id])=>!(state.answers[id]||"").trim()).map(x=>x[1]);const score=Math.round(((need.length-missing.length)/need.length)*100);let note="Thin packet. Expect Phase 0 and Low confidence.";if(score>=70)note="Enough to run a real diagnosis.";if(score>=90)note="Strong packet.";return{score,missing,note}}
function updateMeter(){const fields=STEPS.flatMap(s=>s.fields||[]).map(f=>f[0]);const filled=fields.filter(id=>(state.answers[id]||"").trim()).length;const pct=fields.length?Math.round(filled/fields.length*100):0;document.getElementById("meter").style.width=pct+"%"}
function renderPreview(){document.getElementById("live").textContent=buildIntake();const r=readiness();document.getElementById("chips").innerHTML=`<span class=\"chip ${r.score>=70?"good":"bad"}\">Ready ${r.score}%</span>`+r.missing.slice(0,4).map(m=>`<span class=\"chip bad\">${m}</span>`).join("")}
function flash(msg){const el=document.getElementById("copyStatus");if(el)el.textContent=msg}
async function copyFull(){await navigator.clipboard.writeText(buildFullPacket());flash("Full prompt copied.")}
async function copyIntake(){await navigator.clipboard.writeText(buildIntake());flash("Intake copied.")}
function downloadFull(){const name=(state.answers.name||"game").toLowerCase().replace(/[^a-z0-9]+/g,"-");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([buildFullPacket()],{type:"text/markdown"}));a.download=name+"-game-engineering-packet.md";a.click()}
function exportIntake(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([buildIntake()],{type:"text/markdown"}));a.download="game-intake.md";a.click()}
function resetAll(){if(!confirm("Clear all answers and files?"))return;state.answers={};state.files=[];state.step=0;saveState();renderScreen()}
loadPartB().then(()=>{renderNav();renderScreen();renderPreview();updateMeter()});
